= Contributing

This project is released under the Apache 2.0 license.
If you would like to contribute something, or simply want to hack on the code this document should help you get started.



== Code of Conduct
This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct].
By participating, you are expected to uphold this code.
Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.



== Using GitHub issues
We use GitHub issues to track bugs and enhancements.
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.
Ideally, that would include a small sample project that reproduces the problem.



== Sign the Contributor License Agreement
Before we accept a non-trivial patch or pull request we will need you to https://cla.pivotal.io/sign/spring[sign the Contributor License Agreement].
Signing the contributor's agreement does not grant anyone commit rights to the main repository, but it does mean that we can accept your contributions, and you will get an author credit if we do.
Active contributors might be asked to join the core team, and given the ability to merge pull requests.



== Code Conventions and Housekeeping
None of these is essential for a pull request, but they will all help.
They can also be added after the original pull request but before a merge.

* Make sure all new `.java` files to have a simple Javadoc class comment with at least an `@author` tag identifying you, and preferably at least a paragraph on what the class is for.
* Add the ASF license header comment to all new `.java` files (copy from existing files in the project)
* Add yourself as an `@author` to the `.java` files that you modify substantially (more than cosmetic changes).
* Add some Javadocs.
* A few unit tests would help a lot as well -- someone has to do it.
* If no-one else is using your branch, please rebase it against the current main (or other target branch in the main project).
* When writing a commit message please follow https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions], if you are fixing an existing issue please add `Fixes gh-XXXX` at the end of the commit message (where `XXXX` is the issue number).



== Working with the code
If you don't have an IDE preference we would recommend that you use https://spring.io/tools/sts[Spring Tools Suite] or https://eclipse.org[Eclipse] when working with the code.
We use Buildship for Gradle support.
Other IDEs and tools with Gradle support should also work without issue.



=== Building from source
To build the source you will need to install JDK 17.
The project is built with Gradle. Using the wrapper that is included in the project's source is strongly recommended.

The project can be built from the root directory using the standard Gradle command:

[indent=0]
----
	$ ./gradlew build
----



==== Integration tests
Docker is required for the integration tests that run as part of the default build.
If you don't have Docker installer, or you just want to skip the tests you can build using the `-x integrationTest` option.



=== Importing into Eclipse
You can import the resource's code into any Eclipse based distribution with Buildship, the Eclipse Gradle tooling, installed.



=== Importing into other IDEs
Gradle is well supported by most Java IDEs. Refer to your vendor documentation.
