version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  web:
    image: concourse/concourse:7.9.0
    command: web
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: admin:admin
      CONCOURSE_MAIN_TEAM_LOCAL_USER: admin
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  concourse-worker:
    image: concourse/concourse:7.9.0
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_RUNTIME: containerd
      CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.12.10
    ports: ["8081:8081", "8082:8082"]
    volumes: 
    - ./data/artifactory:/var/opt/jfrog/artifactory
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  registry:
    image: registry:2.8
    ports: ["5000:5000"]
    restart: always
    volumes:
    - ./data/registry/registry:/var/lib/registry
    - ./data/registry/certs:/certs
    - ./data/registry/auth:/auth
